### ISSUE TITLE
Ambiguous reference to member 'bind'

### ISSUE THREAD

**Issue by songhuaixu** [PerfectlySoft/Perfect-NIOCompat#9]
[Error Line](https://github.com/PerfectlySoft/Perfect-NIOCompat/blob/master/Sources/PerfectHTTPServerC/HTTPServer.swift#L153)

`
.bind(address: SocketAddress(ipAddress: serverAddress, port: Int(serverPort)))

`

system: macOS Catalina 10.15
Xcode Version 11.1 (11A1027)

**Comment by kjessup** [comment]
Fixed. Thank you.
